spring.application.name=smart-freelance-hub
spring.datasource.url=jdbc:mysql://localhost:3306/smart_freelance_hub
spring.datasource.username=root
spring.datasource.password=karthice

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
